#!/bin/sh

EMMC=/dev/mmcblk1

while : ; do

	mount -tdevtmpfs none /dev || ( echo "Failed to mount dev"; break )
	mount -tproc none /proc || ( echo "Failed to mount proc"; break )

	modprobe pfe || ( echo "Failed to load pfe driver"; break )

	echo "Wait for the EMMC..."

	while : ; do

		[ -b ${EMMC} ] \
			&& break

		sleep 1
	done

	echo "Create Partition..."
	echo ",," | sfdisk /dev/mmcblk1

	echo "Create Filesystem..."
	mkfs.ext4 -F -O64bit /dev/mmcblk1p1 || ( echo "Failed to create the filesystem"; break )

	mount /dev/mmcblk1p1 /mnt || ( echo "Failed to mount the target device"; break )

	# ether address like bootptab
	ip link set dev eth0 address 00:11:22:33:44:56
	ip link set up eth0

	# wait for eth0 is up (without this, udhcpc will not work)
	while : ; do
		sleep 1

		if [ $(dmesg | tail | grep -c "pfe 4000000.pfe eth0: Link is Up") -gt 0 ]; then
			sleep 1

			udhcpc -f -q -n -t 2 -i eth0

			if [ ! -f /etc/setup ]; then
				echo "Failed to get Setup Information from bootpd - try again..."

				ip link set down eth0
				sleep 1
				ip link set up eth0

			else
				break
			fi
		fi
	done

	. /etc/setup

	if [ -z "${BOOTFILE}" -o -z "${SIADDR}" ]; then
		echo "Missing Setup Information from bootpd"
		break
	fi

	echo "Installing the Filesystem..."

	tftp -g -r ${BOOTFILE} -l - ${SIADDR} | tar -C /mnt -xzf -

	if [ ${?} -ne 0 ]; then
		echo "Failed to get the ${BOOTFILE}"
		break
	fi

	tftp -g -r fitImage -l /mnt/boot/fitImage ${SIADDR}

	if [ ${?} -ne 0 ]; then
		echo "Failed to get the kernel image (fitImage)"
		break
	fi

	echo 'if load ${devtype} ${devnum}:${distro_bootpart} ${load_addr} /boot/fitImage; then' \
	     '    setenv bootargs console=${console} root=/dev/mmcblk1p1 rootwait;' \
	     '    pfe stop;' \
	     '    bootm $load_addr;' \
	     'fi' > /tmp/boot.scr

	mkimage -A arm64 -O linux -T script -C none -n boot.scr -d /tmp/boot.scr /mnt/boot/boot.scr.uimg

	if [ ${?} -ne 0 ]; then
		echo "Failed to create the boot.scr.uimg."
		break
	fi

	sync
	umount /mnt

	echo "+-------------------------------------------+"
	echo "|                                           |"
	echo "|          Installation success             |"
	echo "|                                           |"
	echo "+-------------------------------------------+"

	break
done

/bin/sh


